[build-system]
requires = ["uv_build >=0.12.1, <0.13.0"]
build-backend = "uv_build"

[project]
name = "tqecd"
version = "0.2.1"
authors = [
    { name = "TQEC community", email = "tqec-design-automation@googlegroups.com" },
]
description = "Automatically find detectors in a topologically quantum error corrected computation"
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICENSE"]
keywords = ["topological quantum error correction", "qec", "detectors"]
requires-python = ">= 3.10"

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Natural Language :: English",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: JavaScript",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development :: Libraries",
    "Topic :: Utilities",
    "Typing :: Typed",
]

dependencies = [
    "numpy>=1.22",
    "numpy>=1.24; python_version >= '3.11'",
    "numpy>=1.26; python_version >= '3.12'",
    "numpy>=2.1; python_version >= '3.13'",
    "stim>=1.15.0",
]

[project.urls]
Documentation = "https://tqec.github.io/tqecd/"
Repository = "https://github.com/tqec/tqecd"
Issues = "https://github.com/tqec/tqecd/issues"

[dependency-groups]
test = [
    "pytest<=9.1.0",
    "pytest-cov<=7.1.0",
]

docs = [
    "sphinx<=9.1.0",
    "myst-parser<=4.0.1",
    "pydata-sphinx-theme<=0.19.0",
    "nbsphinx<=0.9.7",
    "pandoc<=2.4",
    "jupyter<=1.1.1",
]

bench = [
    "pyinstrument<=5.1.1",
]

dev = [
    "pre-commit<=4.6.0",
    "ruff==0.16.10",
    "ty>=0.0.1a20",
]

all = [
    { include-group = "test" },
    { include-group = "docs" },
    { include-group = "dev" },
    { include-group = "bench" },
]

[tool.coverage.run]
omit = ["*/*_test.py"]

[tool.coverage.report]
exclude_also = [
    # Don't complain about missing debug-only code:
    "def __repr__",

    # Don't complain if tests don't hit defensive assertion code:
    "raise AssertionError",
    "raise NotImplementedError",

    # Don't complain if non-runnable code isn't run:
    "if __name__ == .__main__.:",

    # Don't complain about abstract methods, they aren't run:
    "@(abc\\.)?abstractmethod",
]

[tool.ruff]
line-length = 100
exclude = ["*.ipynb"]

[tool.ruff.lint]
select = ["I", "E", "W", "F", "UP", "RUF", "NPY", "PERF"]

ignore = [
    "E501",
]
